name: Docker

on:
  push:
    branches:
      - main
  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/cloudrun-go

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20220908, 20221022]
    steps:
      - uses: actions/checkout@v3

      - name: Run test
        run: docker build . --file ${{ matrix.version }}/Dockerfile --tag $IMAGE_ID:${{ matrix.version }}
  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      matrix:
        version: [20220908, 20221022]
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file ${{ matrix.version }}/Dockerfile --tag $IMAGE_ID:${{ matrix.version }}
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          echo Version=${{ matrix.version }}
          docker push $IMAGE_ID:${{ matrix.version }}
